### ISSUE TITLE
Input visi misi

### ISSUE THREAD

**Issue by hijria21** [dimasbp/website-karangtaruna#13]

**Comment by dimasbp** [comment]
**Visi**

- Terwujudnya tali persaudaraan antar pemuda yang berkarakter kuat demi meningkatkan partisipasi pemuda dalam kegiatan lingkungan yang bermasyarakat.
- Terciptanya karang taruna yang bermitra, menginspirasi dan dapat dipercaya demi menyongsong era keterbukaan informasi.


**Misi**

- Merekrut pemuda lingkungan RW.006.
- Menjadi wadah pengembangan karakter dan jiwa kepemimpinan talenta muda RW.006 baik MENKOMINFO, MENPORA, dan MENSOS.
- Menjadi mitra strategis sebagai masyrakat RW.006.
- Menjadi garda terdepan branding karang taruna di dalam dan di luar lingkungan RW.006.
