### ISSUE TITLE
Black Box Testing

### ISSUE THREAD

**Issue by dimasbp** [dimasbp/website-karangtaruna#18]

**Comment by hijria21** [comment]
[Black_Box_Testing.docx](https://github.com/dimasbp/website-karangtaruna/files/1283926/Black_Box_Testing.docx)

**Comment by hijria21** [comment]
[Black_Box_Testing.docx](https://github.com/dimasbp/website-karangtaruna/files/1291037/Black_Box_Testing.docx)

**Comment by hijria21** [comment]
sudah selesai Black Box Testing

**Comment by dimasbp** [comment]
Mantap jal
