### ISSUE TITLE
Gambar untuk Home Page

### ISSUE THREAD

**Issue by axelxio** [dimasbp/website-karangtaruna#2]

**Comment by axelxio** [comment]
@dimasbp gambarnyayang mana?
![home](https://user-images.githubusercontent.com/12684813/29104749-330a61d6-7cf2-11e7-8c9b-a7bfdd686d8f.jpg)
![img-20161002-wa0031](https://user-images.githubusercontent.com/12684813/29104777-79fcb6fc-7cf2-11e7-97b1-f8014ebe1b0e.jpg)

**Comment by dimasbp** [comment]
Gambar yang kedua

**Comment by axelxio** [comment]
ok
