### ISSUE TITLE
transparansi logo

### ISSUE THREAD

**Issue by axelxio** [dimasbp/website-karangtaruna#4]

**Comment by axelxio** [comment]
@hijria21 jal upload sini kalo ud

**Comment by hijria21** [comment]
oke

**Comment by hijria21** [comment]
![logo karang taruna](https://user-images.githubusercontent.com/16078906/29206930-47e3d3fe-7eae-11e7-99b7-ebaaadbb5d2b.png)

**Comment by hijria21** [comment]
![logo web](https://user-images.githubusercontent.com/16078906/29207173-617dbeb4-7eaf-11e7-8000-4fd6934a0ed5.png)
coba yang ini aja

**Comment by axelxio** [comment]
oke makasi
