### ISSUE TITLE
Membuat Struktur Navigasi Visitor

### ISSUE THREAD

**Issue by dimasbp** [dimasbp/website-karangtaruna#7]

**Comment by hijria21** [comment]
![image](https://user-images.githubusercontent.com/16078906/29207508-99ca0560-7eb0-11e7-80bd-7ef4a67e08a5.png)

**Comment by hijria21** [comment]
Struktur Navigasi untuk visitor telah selesai dibuat

**Comment by dimasbp** [comment]
Oke makasih jal
