### ISSUE TITLE
Membuat Struktur Navigasi Administrator

### ISSUE THREAD

**Issue by dimasbp** [dimasbp/website-karangtaruna#8]

**Comment by hijria21** [comment]
![image](https://user-images.githubusercontent.com/16078906/29207418-4e5928ea-7eb0-11e7-8cdf-cd1f85d0a2df.png)

**Comment by hijria21** [comment]
Struktur Navigasi untuk admin telah selesai dibuat

**Comment by dimasbp** [comment]
Sip
